errorMetadata = {
        "GITHUB_ERROR_404" : { "description" : "resource not found" , "message" : "repo {param} not found" },
        "GITHUB_ERROR_405" : { "description" : "resource not found" , "message" : "branch {param} not found" },
        "GITHUB_ERROR_401" : { "description" : "connecting Github" , "message" : "access token not valid" },
        "GITHUB_ERROR_999" : { "description" : "unhandled error" , "message" : "unhandled error" },
        "REST_STEP_ERROR_302" : { "description" : "too many redirects" , "message" : "too many redirects when requesting resource: {url}" },
        "REST_STEP_ERROR_405" : { "description" : "unsupported HTTP method" , "message" : "method: {method} not allowed, try GET or POST" },
        "REST_STEP_ERROR_422" : { "description" : "unprocessable entity" , "message" : "response code: {actualStatusCode} != expected code: {expectedStatusCode}" },
        "REST_STEP_ERROR_423" : { "description" : "unprocessable entity" , "message" : "response param with path: {path} != expected value: {expectedValue}" },
        "REST_STEP_ERROR_424" : { "description" : "unprocessable entity" , "message" : "variable in path: {path} not found in response" },
        "REST_STEP_ERROR_425" : { "description" : "unprocessable entity" , "message" : "extracting variables from response, unhandled error" },
        "REST_STEP_ERROR_426" : { "description" : "unprocessable entity" , "message" : "url required, url passed: {url}" },
        "REST_STEP_ERROR_427" : { "description" : "unprocessable entity" , "message" : "missing schema, url provided: {url}" },
        "REST_STEP_ERROR_428" : { "description" : "unprocessable entity" , "message" : "invalid schema, url provided: {url}, protocol is most likely not recognized, or not supported by the underlying network transport" },
        "REST_STEP_ERROR_429" : { "description" : "unprocessable entity" , "message" : "invalid url provided: {url}, please check for invalid chars in the url" },
        "REST_STEP_ERROR_430" : { "description" : "unprocessable entity" , "message" : "invalid headers provided: {headers}, please all the header values are strings" },
        "REST_STEP_ERROR_431" : { "description" : "unprocessable entity" , "message" : "resource: {url} response body was not properly chunk-encoded" },
        "REST_STEP_ERROR_432" : { "description" : "unprocessable entity" , "message" : "resource: {url} response body decoding failed, please check headers" },
        "REST_STEP_ERROR_434" : { "description" : "unprocessable entity" , "message" : "retry attempts exceeded for the requested resource:{url}" },
        "REST_STEP_ERROR_436" : { "description" : "unprocessable entity" , "message" : "proxy url provided is invalid" },
        "REST_STEP_ERROR_437" : { "description" : "unprocessable entity" , "message" : "invalid proxy server, check proxy credentials as well" },
        "REST_STEP_ERROR_438" : { "description" : "unprocessable entity" , "message" : "invalid SSL certificate for the service:{host}" },
        "REST_STEP_ERROR_504" : { "description" : "gateway timeout" , "message" : "service not reachable host:{host} port:{port}" },
        "REST_STEP_ERROR_506" : { "description" : "gateway timeout" , "message" : "service timed out when requesting {url}" },
        "REST_STEP_ERROR_999" : { "description" : "unhandled error" , "message" : "unhandled error" },
}