name: CE Configuration
metadata:
    retry_policy:
      init_interval: 1
      backoff_coefficient: 2
      max_interval: 100
      max_attempts: 10
    version: 1.0
dependencies:
  - name: cpe_discovery
    version: 1.2.3
steps:
{% if demo %}
  - name: Clean up vrf configs
    file: l3vpn-provisioning/clean_up_vrf_config.yml
{% endif %}
  - name: Fetch CE configs
    file: l3vpn-provisioning/ce-provisioning/Fetch_CE_configs.yml
  
  - name: show_save_ce_config
    file: l3vpn-provisioning/ce-provisioning/show_save_ce_config.yml

  - name: add_vrf_definition
    file: l3vpn-provisioning/ce-provisioning/add_vrf_definition.yml

  - name: add_prefix_lists
    file: l3vpn-provisioning/ce-provisioning/add_prefix_lists.yml

  - name: add_route_maps
    file: l3vpn-provisioning/ce-provisioning/add_route_maps.yml

  - name: validate save ce config 
    file: l3vpn-provisioning/ce-provisioning/validate_save_ce_config.yml