name: Clean up vrf configs
hostname: "{{pe.management_ip}}"
description: deleting vrf configs from the device
configType: CLI
config: |
  terminal length 0
  enable
  config t
  no vrf definition VRF_Capgemini
  no route-map Capgemini-VRF-IMPORT
  no route-map Capgemini-VRF-EXPORT
  exit