name: CE Configuration
metadata:
    retry_policy:
      init_interval: 1
      backoff_coefficient: 2
      max_interval: 100
      max_attempts: 10
    version: 1.0
dependencies:
  - name: cpe_discovery
    version: 1.2.3
steps:
{% if demo %}
  - name: Clean up vrf configs
    file: clean_up_vrf_config.yml
{% endif %}
  - name: Fetch CE configs
    file: Fetch_CE_configs.yml
  
  - name: show_save_ce_config
    file: show_save_ce_config.yml

  - name: config ce subnet
    file: config ce subnet.yml

  - name: validate save ce config
    file: validate save ce config.yml