name: Clean up vrf configs
hostname: sandbox-iosxe-latest-1.cisco.com
description: deleting vrf configs from the device
configType: CLI
config: |
  terminal length 0
  enable
  config t
  no vrf definition VRF_Capgemini
  no route-map Capgemini-VRF-IMPORT
  exit