name: PE Configuration
metadata:
    retry_policy:
      init_interval: 1
      backoff_coefficient: 2
      max_interval: 100
      max_attempts: 10
    version: 1.0
dependencies:
steps:
{% if demo %}
  - name: Clean up vrf configs
    file: clean_up_vrf_config.yml
{% endif %}
  - name: Fetch PE configs
    file: Fetch_PE_configs.yml

  - name: show_save_pe_config
    file: show_save_pe_config.yml

  - name: config customer vrf
    file: config customer vrf.yml

  - name: validate save pe config
    file: validate save pe config.yml