name: Validate and Save CE Config
hostname: sandbox-iosxe-latest-1.cisco.com
description: validate device configuration and save
configType: NETCONF
request:
  type: FETCH
  payload: |
    <interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
      <interface>
        <enabled>true</enabled>
      </interface>
    </interfaces>
  validate:
    $..interface[?(@.description =~ ".*RESTCONF.*")].name: loopbackInterface
  variables:
    managementInterface: $..interface[?(@.description =~ ".*MANAGEMENT.*")]